In [1]:
a = [1,2,3,4,5]

In [3]:
import numpy as np
arr = np.array(a)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
matr_zero = np.zeros((2,3))
print(matr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
matr_ones = np.ones((2,3))
print(matr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [12]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [13]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]
